eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#okta:
#  oauth2:
#    issuer: https://dev-199963.okta.com/oauth2/default
#    audience: api://default
